# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-10-12 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='respuestasUser',
            fields=[
                ('idResp', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('resp', models.TextField()),
            ],
        ),
    ]
